version: '3.3'

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wp
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/db
      o: bind

networks:
  inception:

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    networks:
      - inception
    secrets:
      - db_root_password
      - db_password

  wordpress:
    build: requirements/wordpress
    container_name: wp-php
    restart: always
    expose:
      - "9000"
    volumes:
      - web:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    networks:
      - inception
    depends_on:
      - mariadb
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt