FROM debian:bullseye

RUN apt-get update && apt-get install -y nginx openssl \
&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/nginx/ssl/localhost.key \
	-out /etc/nginx/ssl/localhost.crt \
	-subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

COPY tools/default.config /etc/nginx/sites-available/default
RUN ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
